### PR TITLE
working demo for Brennenstuhl RC 3600

### PR DESCRIPTION
**Pull request by mattvenn**
Hi there and thanks for the rc switch code. I made some modifications and added an example for the Brennenstuhl RC 3600 plugs. Unfortunately, they work on some more complicated coding system than I have time or energy to reverse engineer. So I have just included 3 working on and off codes that I recorded from the remote control.

### CODE REVIEW

**Comment by vvhof** [comment]
Confirmed working.

**Comment by roccomuso** [comment]
Is Brennenstuhl RCS 1000 N supported?

**Comment by mattvenn** [comment]
no idea, try it and see.

On 26 November 2015 at 16:32, Rocco Musolino <notifications@github.com>
wrote:

> Is Brennenstuhl RCS 1000 N supported?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sui77/rc-switch/pull/4#issuecomment-159955060>.
>



-- 
Matthew Venn
mattvenn.net

**Comment by roccomuso** [comment]
I gotta buy them first. Any tips would be appreciated.

**Comment by mattvenn** [comment]
I would buy a brand that is known working. The plugs I got are over
complicated in my opinion and more difficult to reverse engineer.

On 27 November 2015 at 01:30, Rocco Musolino <notifications@github.com>
wrote:

> I gotta buy them first. Any tips would be appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sui77/rc-switch/pull/4#issuecomment-160015466>.
>



-- 
Matthew Venn
mattvenn.net

**Comment by roccomuso** [comment]
Tested with the Arendo and Brennenstuhl RCS 1000 N outplugs, both working great.

**Comment by fingolfin** [comment]
As far as I can tell, this is obsolete: the protocol 4 it adds has been added as protocol 5 already, by PR #11 -- can you confirm?

**Comment by fingolfin** [comment]
Also, if you have time, it would be great if you could add information about your sockets on https://github.com/sui77/rc-switch/wiki/List_KnownDevices

**Comment by roccomuso** [comment]
@fingolfin I'm gonna do it right now.

PS. Does rc-switch receive also codes from other kind of RF sensors? like PIR 433mhz sensor and Door sensor?

**Comment by fingolfin** [comment]
Depends on what protocols they use. But in principle, this lib can decode more things than just switches. I guess it's a matter of experimenting.

**Comment by roccomuso** [comment]
Because the 433Utils library by Ninjablock team can, and it's based on RCswitch.

**Comment by rotv** [comment]
Pull request #16 is an attempt to combine the efforts of both communities (Arduino & RPi), i.e. making the Ninjablock library compile directly towards an rc-switch commit (and not to a three year old copy). I did notice however that the recent commits have created conflicts so I'll update the PR when I get time for it.

**Comment by roccomuso** [comment]
@rotv and @fingolfin thanks for both your efforts. Really appreciated.

**Comment by fingolfin** [comment]
@rotv Thanks, looking forward to your updated #16 then.

**Comment by fingolfin** [comment]
@mattvenn So I now see I missed one aspect: As I understand it, you have three pairs of working on/off codes, using a slight modification of protocol 2 (which now is in rc-switch, as protocl 5). You are asking for a "high level" interface to generate these codes for the `Brennenstuhl RC 3600`, correct? The codes you provided are these:
```
char * on_codes[] = {
    "101001000110001010101100",
    "101011011010011000000101",
    "101000001100100101111110",
};

char * off_codes[] = {
    "101001110111110010111100",
    "101000010101101001000101",
    "101010111011000001011110",
};
```


Interestingly I have the `Brennenstuhl RC 2044` set, which looks similar from the outside. But for that, I had to use a completly different set of codes, namely a modification of protocol 3 (where the sync signal had to be changed from 1,71 to 30,71). The codes I get are also different; indeed, the same button on the remote produces 4 different codes, and the remote cycles between them. I have a theory about that (they might be using a data whitening technique, e.g. similar to http://www.semtech.com/images/datasheet/AN1200.18_STD.pdf), but have not verified that. Luckil, any of the codes can be sent at any time and will be accepted.

**Comment by fingolfin** [comment]
Some relevant links:
* https://forum.pilight.org/Thread-Brennenstuhl-RC-3600
* https://github.com/pimatic/pimatic/issues/386
* https://github.com/pilight/pilight/pull/215

I think it would be good to document these things in a central place and implement as much as possible (in particular to avoid duplicated work -- my wife and me worked on the same issue for the RC 2044 a year ago, and basically discovered the same things as described above, but then put that anywhere :/. I am pretty sure lots of other people out there went through the same... perhaps we can extend the Wiki to cover more protocols and concrete devices, to help people who google for this stuff)

**Comment by rotv** [comment]
Now #16 is ready to be merged again. One interesting experience gained is that I can send codes with varying pulse length (protocol 1, pulse length set between 150-350 us) and get the sockets to understand, but to read signals from my two remote controls I must specify 140 us and 150 us respectively.

**Comment by fingolfin** [comment]
As it is, this pull request is unmergable, and at least partially obsolete. Also, so far, no reaction by @mattvenn

If there is anything in here anybody deems useful, please open a fresh pull request. If you think there are issues mentioned in the discussion that should be addressed, please open an issue (one for each problem) where you try to describe the problem cleary.

Thanks!

**Pull request closed without merging**
