### PR TITLE
@PlatformIO Library Registry manifest file

### PR DESCRIPTION
**Pull request by valeros**
Description
* This library in Web Registry: http://platformio.org/lib/show/246/RCSwitch
* Specification: [library.json](http://docs.platformio.org/en/latest/librarymanager/config.html)
* Library Manager: http://docs.platformio.org/en/latest/librarymanager/index.html

### CODE REVIEW

**Comment by fingolfin** [comment]
Your description is not very descriptive :-). In paticular, it remains unclear what this pull request is needed for? You link to http://platformio.org/lib/show/246/RCSwitch which seems to already have all the information you included in that `library.json`.

Hmm, it also seems this file only specifies Arduino as platform, but not Raspberry Pi, which gives a weird clash between description text and content... Ah well, not complaining, just observing :)


(Side remark: It's also somewhat unfortunate that platformio chose JSON as a standard, so one cannot put comments in that file, e.g. to explain that the file is related to platformio -- so if you don't know what the file is about, you can't easily find out

**Comment by ivankravets** [comment]
@fingolfin What file format is comfortable for you? 

> In paticular, it remains unclear what this pull request is needed for?

The some user requested to add your library https://github.com/platformio/platformio-libmirror/issues/45

**Comment by ivankravets** [comment]
@valeros please extend manifest with

```json
{
    "frameworks": [
        "arduino",
        "energia",
        "wiringpi"
    ],
    "platforms": "*"
}
```

**Comment by fingolfin** [comment]
I still don't see *any* explanation here why this is needed, and what it does.

If you want this to be merged, please explain what it does and *why* (on a higher level than "it adds this file"); for example, describe a usecase that is helped by this; describe a scenario where a user benefits from this, and how.

**Comment by bau-sec** [comment]
@fingolfin This registers rc-switch with PlatformIO so users can easily install the library from PlatformIO's CLI/IDE-plugin/etc. The reason you're seeing all the information posted on http://platformio.org/lib/show/246/RCSwitch is because the rc-switch library.json file is being sourced from https://github.com/valeros/rc-switch/blob/patch-1/library.json (the branch this PR is based on).

This patch should be merged (possibly with modifications to better specify compatible platforms and frameworks) and the PlatformIO registry should be updated to point to this repo instead. Otherwise the rc-switch authors aren't in control of the information provided to PlatformIO users about compatibility, version, authorship, etc.

For more info: http://docs.platformio.org/en/latest/librarymanager/creating.html

**Comment by fingolfin** [comment]
@bau-sec Thanks, at last somebody describe what this is about. So I am going to merge this, based on what you wrote. I'll not make any modifications, because quite frankly, I don't want to bother learning about platformio. But if you know how to use it and can come up with a reasonable pull request, of course we can merge that.

**Comment by ivankravets** [comment]
@fingolfin thanks a lot that merged. I've just switched library config to original from this repository.

@bau-sec thank you too for explanations.

**Pull request merged**
