### PR TITLE
Removed unnecessary 'extern C'-block

### PR DESCRIPTION
**Pull request by rotv**
According to discussion in PR #16.

### CODE REVIEW

**Comment by NicoHood** [comment]
why are those typedefs even needed? You should never use such an unusual definitions as "byte" or "boolean". Its very bad that they even implemented that for Arduino.

**Comment by fingolfin** [comment]
@rotv thanks, but perhaps go a bit further: I don't see why you need to #define CHANGE as the only line involving it is #if'defed out on RaspberryPi. And why is stddef.h included? The comment suggests that it is for NULL, but NULL is not used by rc-switch.

**Comment by fingolfin** [comment]
Oh, and it says `PROGMEM och _P functions` in one of the comments -- does `och` stand for `and`? or what?

**Comment by fingolfin** [comment]
I made the relevant changes myself now. Hopefully that didn't break anything, but if it did, I hope we can quickly fix it

**Comment by NicoHood** [comment]
Why do I get a downvote instead of an answer? I think such a typedef (apart from the fact that it does not make sense to use one) should not be placed inside a library like this. It should be placed inside an Arduino friendly api for the raspi or the usercode itself. Otherwise you will get warnings of redeclaring those typedefs if every lib would do so.

**Comment by rotv** [comment]
"och" is Swedish for "and", you passed the language test! (of course it wasn't a mistake on my side ;) )

**Comment by fingolfin** [comment]
@NicoHood First off: those typedefs are gone now. As to the downvote: You made wide, sweeping claims ("you should never...") without substantiating them, and in addition were borderline off-topic for this pull request to start with (it didn't add those typedefs, after all, just cleaned up existing code). Finally, at least to me, your comments sounds quite arrogant (implying that whoever "did this" must have been a moron, at least compared to you).

Lesson to take from this: When collaborating on open source, it doesn't just matter whether you are "right" or not, but rather also the way you express yourself (i.e. whether and how you explain your point of view; how you phrase things; etc.).

**Comment by fingolfin** [comment]
@rotv thanks for the clarification :-). It would be great if you could verify the most recent code (with lots of changes) still works for you on Raspberry Pi -- I don't have one to test. If I broke anything: sorry about that, I hope you can fix it :-P, or tell me what I broke, then I'll try to fix it :-).

**Comment by rotv** [comment]
I saw that you made some nice cleanups, thanks! Can't compile rc-switch for the moment though, see #51

**Pull request merged**
