### PR TITLE
Added support for Holtek's HT12E encoder/decoders

### PR DESCRIPTION
**Pull request by cat101**
Added support for Holtek's HT12E encoder/decoders

### CODE REVIEW

**Comment by Adrien-P** [comment]
@cat101 Just tested your protocol definition on my HT12E based remote plugs and it worked like a charm.
Thanks!

**Comment by cat101** [comment]
@sui77 I'm new to this project. Do you need me to do anything else before you can merge the changes to the master branch? Cheers

**Comment by XciD** [comment]
Hi cat101, Thank for that working great for me.
Could you share how do you handle finding the protocol ?

**Comment by cat101** [comment]
Hi @XciD, I put together the circuit I show [here](https://github.com/cat101/rf433-to-rest) but instead of having the RPi I hooked and oscilloscope. Then it is just a matter of setting a trigger to freeze the "bit train". In this case the analysis was simple since the issue was timing and the 0 & 1 were inverted. I have a bit of practice doing this because I have done it several time for infrared remotes...I use the same technique..just change the receiver.

Let me know if you need more details

**Comment by Martin-Laclaustra** [comment]
@XciD
You can manually record and interpret your signals with [SimpleRcScanner](https://github.com/sui77/SimpleRcScanner) and create a protocol.

**Comment by jeffborg** [comment]
@cat101 This worked like a charm for me as well. Thanks!

**Pull request merged**
